version: '3'
services:
  property_ms:
    build: .
    command: python index.py -ms property
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - db-variables.env
  operations_ms:
    build: .
    command: python index.py -ms operations
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - db-variables.env